name: Update F1 Fantasy data

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install skelmis-f1-fantasy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update script
        env:
          F1_USER_GUID: ${{ secrets.F1_USER_GUID }}
          F1_TOKEN: ${{ secrets.F1_TOKEN }}
        run: python scripts/get_round_data.py

      - name: Update README with season stats
        run: python scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "mzafram2001@gmail.com"
          git config --local user.name "mzafram2001"
                
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: Update F1 Fantasy data & README" && git push)
